### ISSUE TITLE
JSON_PRETTY_PRINT as an option

### ISSUE THREAD

**Issue by ctrix** [akrabat/rka-content-type-renderer#6]
It seems that for the application/json output format, the flag **JSON_PRETTY_PRINT** is always used.

When the output of an API is big, it would be extremely useful to have some option to disable this behaviour and remove that flag.

If it makes sense, can you please add this feature ?

**Comment by akrabat** [comment]
@ctrix Does PR #7 work for you?

**Comment by ctrix** [comment]
Hello Akrabat, thanks.
I think it can work. I only have one doubt:

If $pretty is false, you're removing both flags:
JSON_PRETTY_PRINT | JSON_UNESCAPED_SLASHES

Shouldn't JSON_UNESCAPED_SLASHES be preserved and set in all cases ? (mainly for backward compatibility)

**Comment by akrabat** [comment]
JSON_UNESCAPED_SLASHES is for readability too, so I think it's also not needed.
